'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { AppSettings, defaultSettings } from '@/lib/config/settings'

const plans = [
  { name: 'Veg', price: '₹1,499', note: 'Comforting vegetarian lunch', items: ['Rice, dal / sambar', 'Seasonal vegetable', 'Chapati, curd & pickle', 'Paneer on applicable day'] },
  { name: 'Non-Veg', price: '₹1,499', note: 'Home-style lunch with chicken', items: ['Rice, dal & vegetable', 'Chapati, curd & pickle', 'Egg on applicable day', 'Chicken on applicable day'] },
]

const weeklyMenu = [
  { day: 'Monday', items: [{ label: 'Rice', type: 'staple' }, { label: 'Dal Curry', type: 'veg' }, { label: 'Vegetable Fry', type: 'veg' }, { label: 'Curd', type: 'staple' }, { label: 'Pickle', type: 'staple' }, { label: 'Papad', type: 'staple' }] },
  { day: 'Tuesday', items: [{ label: 'Rice', type: 'staple' }, { label: 'Sambar', type: 'veg' }, { label: 'Vegetable Fry', type: 'veg' }, { label: 'Curd', type: 'staple' }, { label: 'Pickle', type: 'staple' }, { label: 'Papad', type: 'staple' }] },
  { day: 'Wednesday', items: [{ label: 'Rice', type: 'staple' }, { label: 'Dal Curry', type: 'veg' }, { label: 'Paneer (Veg)', type: 'veg' }, { label: 'Chicken (Non-Veg)', type: 'nonveg' }, { label: 'Curd', type: 'staple' }, { label: 'Pickle', type: 'staple' }] },
  { day: 'Thursday', items: [{ label: 'Rice', type: 'staple' }, { label: 'Sambar', type: 'veg' }, { label: 'Vegetable Fry', type: 'veg' }, { label: 'Curd', type: 'staple' }, { label: 'Pickle', type: 'staple' }, { label: 'Papad', type: 'staple' }] },
  { day: 'Friday', items: [{ label: 'Rice', type: 'staple' }, { label: 'Dal Curry', type: 'veg' }, { label: 'Vegetable Fry', type: 'veg' }, { label: 'Curd', type: 'staple' }, { label: 'Pickle', type: 'staple' }, { label: 'Papad', type: 'staple' }] },
  { day: 'Saturday', items: [{ label: 'Rice', type: 'staple' }, { label: 'Sambar', type: 'veg' }, { label: 'Vegetable Fry', type: 'veg' }, { label: 'Curd', type: 'staple' }, { label: 'Pickle', type: 'staple' }, { label: 'Papad', type: 'staple' }] },
]

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [settings, setSettings] = useState<AppSettings>(defaultSettings)

  useEffect(() => {
    fetch('/api/settings').then(response => response.json()).then(setSettings).catch(() => undefined)
  }, [])

  const deliveryDays = settings.delivery.days.join(' - ')
  const trialPrice = `₹${settings.plans.trialPrice.toLocaleString('en-IN')}`
  const monthlyPrice = `₹${settings.plans.monthlyPrice.toLocaleString('en-IN')}`
  return <main>
    <header className="site-header"><Link href="/" className="brand"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Sep%2012%2C%202026%2C%2005_02_26%20PM-nfLMqUqsIl5jluhhngWFv1fIGayTQN.png" alt="Grandma's Lunchbox logo" /><span>Grandma&apos;s<br /><b>Lunchbox</b></span></Link><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">☰</button><nav className={menuOpen ? 'nav open' : 'nav'}><a href="#plans">Plans</a><a href="#menu">Menu</a><a href="#how">How it works</a><a href="#faq">FAQ</a><Link className="button small" href="/order?plan=trial">Start trial</Link></nav></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">{settings.location.city.toUpperCase()} • {settings.location.state.toUpperCase()}</p><h1>Home-cooked lunch, <em>while you&apos;re at work.</em></h1><p className="hero-text">Freshly prepared meals delivered to offices in {settings.location.city}, {settings.location.state} from {deliveryDays}. The comfort of home, right at your pickup point.</p><div className="hero-actions"><Link className="button" href="/order?plan=trial">Start {settings.delivery.trialDays}-day trial <span>{trialPrice} on delivery</span></Link><a className="text-link" href="#plans">View monthly plans <span>→</span></a></div><div className="delivery-note"><span>●</span><b>{deliveryDays}</b><i /> <b>{settings.delivery.time}</b></div></div><div className="hero-art"><img className="hero-logo" src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Sep%2012%2C%202026%2C%2005_02_26%20PM-nfLMqUqsIl5jluhhngWFv1fIGayTQN.png" alt="Grandma cooking and serving a home-style lunch" /><div className="sun" /><div className="meal-card"><div className="meal-top"><span>Today&apos;s lunch</span><span className="fresh">Fresh today</span></div><div className="thali"><div className="dish rice" /><div className="dish dal" /><div className="dish veg" /><div className="dish roti" /></div><p>Made with care, like home.</p></div><div className="leaf leaf-one" /><div className="leaf leaf-two" /></div></section>
    <section className="trust-strip"><p><span>✦</span> Made for working professionals</p><p><span>✦</span> Simple weekday subscriptions</p><p><span>✦</span> No daily ordering</p></section>
    <section className="section" id="why"><div className="section-heading"><p className="eyebrow">A little bit of home</p><h2>Lunch that fits your workday.</h2><p>We keep it simple: fresh food, a familiar menu, and a reliable pickup at your office.</p></div><div className="feature-grid">{[['⌂','Home cooked','Prepared with the comfort and care of home food.'],['✦','Fresh every day','Lunch is prepared fresh for the day.'],['◌','Made for your workday','Designed around weekday office schedules.'],['↗','Simple plans','No complicated ordering every day.']].map(([icon,title,text]) => <article className="feature" key={title}><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section plans-section" id="plans"><div className="section-heading centered"><p className="eyebrow">Choose your comfort</p><h2>Good food, made easy.</h2><p>Both plans include a complete home-style lunch, every {settings.delivery.days[settings.delivery.days.length - 1] || 'Saturday'}.</p></div><div className="plan-grid">{plans.map(plan => <article className="plan-card" key={plan.name}><div className="plan-head"><div><span className="plan-label">{plan.name.toUpperCase()}</span><h3>{monthlyPrice}<small>/month</small></h3></div><span className="plan-dot" /></div><p className="plan-note">{plan.note}</p><ul>{plan.items.map(item => <li key={item}>✓ {item}</li>)}</ul><Link className="button outline" href={`/order?meal=${plan.name.toLowerCase()}`}>Choose {plan.name}</Link></article>)}</div><div className="trial-banner"><div><p className="eyebrow">Start small</p><h3>Try Grandma&apos;s Lunchbox for {settings.delivery.trialDays} days.</h3><p>No payment today. Pay {trialPrice} on your first delivery and see how good your workday can feel.</p></div><Link className="button light" href="/order?plan=trial">Start {settings.delivery.trialDays}-day trial <span>→</span></Link></div></section>
    <section className="section menu-section" id="menu"><div className="section-heading centered"><p className="eyebrow">This week&apos;s menu</p><h2>Home-cooked, daily.</h2><p>Fresh home-style meals planned for every weekday.</p></div><div className="menu-card"><table><thead><tr><th>Day</th><th>Menu</th></tr></thead><tbody>{weeklyMenu.map(({ day, items }) => <tr key={day}><td className="menu-day-cell"><span className="menu-day-name"><span className="menu-day-dot" />{day}</span></td><td className="menu-items-cell"><div className="menu-chips">{items.map(({ label, type }) => <span className={`menu-chip ${type}`} key={`${day}-${label}`}>{label}</span>)}</div></td></tr>)}</tbody></table><p className="menu-foot-note">Menu may vary slightly based on seasonal availability.</p></div></section>
    <section className="section process" id="how"><div className="section-heading centered"><p className="eyebrow">From our kitchen to your desk</p><h2>How it works</h2></div><div className="steps">{[['01','Choose your plan'],['02','Enter your details'],['03','Pay on first delivery'],['04',`Collect in ${settings.location.city}`]].map(([number,title],i) => <div className="step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{['Pick Veg or Non-Veg, trial or monthly.','Tell us where you work and where to meet.','No payment today; pay when your first lunch is delivered.',`Lunch is ready ${settings.delivery.time}, ${deliveryDays}.`][i]}</p></div></div>)}</div></section>
    <section className="area-section"><div><p className="eyebrow">Where we deliver</p><h2>{settings.location.areaDescription}</h2><p>We&apos;re starting close to home, serving selected office locations in {settings.location.city}. Choose your building and pickup point during signup.</p><Link className="text-link" href="/order">Check availability <span>→</span></Link></div><div className="map-card" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,0.06), rgba(255,255,255,0.06)), url('/Sri_City_office_and_flags.jpg')", backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }} /></section>
    <section className="section faq-section" id="faq"><div className="section-heading centered"><p className="eyebrow">Questions, answered</p><h2>Good to know.</h2></div><div className="faq-grid">{[['What time is lunch delivered?',`${settings.delivery.time} from ${deliveryDays}.`],['Which days do you deliver?',`${deliveryDays}.`],['Can I choose Veg or Non-Veg?','Yes, choose your preference when you place your order.'],['Is there a trial?',`Yes, try ${settings.delivery.trialDays} days for ${trialPrice}.`],['How do I receive my lunch?','Select an available building and pickup point during registration.'],['Can I pause my subscription?','Pause and subscription management will be added in a future update.']].map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <footer className="footer"><div className="brand"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Sep%2012%2C%202026%2C%2005_02_26%20PM-nfLMqUqsIl5jluhhngWFv1fIGayTQN.png" alt="Grandma&apos;s Lunchbox logo" /><span>Grandma&apos;s<br /><b>Lunchbox</b></span></div><p>Home-cooked lunch for working professionals.<br />{settings.location.city}, {settings.location.state}</p><div><b>{settings.contact.name}</b><br />WhatsApp: {settings.contact.whatsapp}</div><small>© 2026 Grandma&apos;s Lunchbox. Made with care.</small></footer>
  </main>
}
