'use client'

import Link from 'next/link'
import { useState } from 'react'

const plans = [
  { name: 'Veg', price: '₹1,299', note: 'Comforting vegetarian lunch', items: ['Rice, dal / sambar', 'Seasonal vegetable', 'Chapati, curd & pickle', 'Paneer on applicable day'] },
  { name: 'Non-Veg', price: '₹1,299', note: 'Home-style lunch with chicken', items: ['Rice, dal & vegetable', 'Chapati, curd & pickle', 'Egg on applicable day', 'Chicken on applicable day'] },
]

const weeklyMenu = [
  { day: 'Monday', items: [['Rice', 'staple'], ['Dal Curry', 'veg'], ['Vegetable Fry', 'veg'], ['Chapathi', 'staple'], ['Curd', 'staple'], ['Pickle', 'staple']] },
  { day: 'Tuesday', items: [['Rice', 'staple'], ['Sambar', 'veg'], ['Vegetable Fry', 'veg'], ['Chapathi', 'staple'], ['Curd', 'staple'], ['Pickle', 'staple']] },
  { day: 'Wednesday', items: [['Rice', 'staple'], ['Dal Curry', 'veg'], ['Paneer (Veg)', 'veg'], ['Chicken (Non-Veg)', 'nonveg'], ['Chapathi', 'staple'], ['Curd', 'staple'], ['Pickle', 'staple']] },
  { day: 'Thursday', items: [['Rice', 'staple'], ['Sambar', 'veg'], ['Vegetable Fry', 'veg'], ['Chapathi', 'staple'], ['Curd', 'staple'], ['Pickle', 'staple']] },
  { day: 'Friday', items: [['Rice', 'staple'], ['Dal Curry', 'veg'], ['Vegetable Fry', 'veg'], ['Chapathi', 'staple'], ['Curd', 'staple'], ['Pickle', 'staple']] },
]

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main>
    <header className="site-header"><Link href="/" className="brand"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Sep%2012%2C%202026%2C%2005_02_26%20PM-nfLMqUqsIl5jluhhngWFv1fIGayTQN.png" alt="Grandma's Lunchbox logo" /><span>Grandma&apos;s<br /><b>Lunchbox</b></span></Link><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">☰</button><nav className={menuOpen ? 'nav open' : 'nav'}><a href="#plans">Plans</a><a href="#menu">Menu</a><a href="#how">How it works</a><a href="#faq">FAQ</a><Link className="button small" href="/order?plan=trial">Start trial</Link></nav></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">ITPL • WHITEFIELD • BENGALURU</p><h1>Home-cooked lunch, <em>while you&apos;re at work.</em></h1><p className="hero-text">Freshly prepared meals delivered to ITPL offices every weekday. We start serving from October 15, 2026 — the comfort of home, right at your pickup point.</p><div className="hero-actions"><Link className="button" href="/order?plan=trial">Start 5-day trial <span>₹299 on delivery</span></Link><a className="text-link" href="#plans">View monthly plans <span>→</span></a></div><div className="delivery-note"><span>●</span><b>Monday – Friday</b><i /> <b>around 12:30 PM</b></div></div><div className="hero-art"><img className="hero-logo" src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Sep%2012%2C%202026%2C%2005_02_26%20PM-nfLMqUqsIl5jluhhngWFv1fIGayTQN.png" alt="Grandma cooking and serving a home-style lunch" /><div className="sun" /><div className="meal-card"><div className="meal-top"><span>Today&apos;s lunch</span><span className="fresh">Fresh today</span></div><div className="thali"><div className="dish rice" /><div className="dish dal" /><div className="dish veg" /><div className="dish roti" /></div><p>Made with care, like home.</p></div><div className="leaf leaf-one" /><div className="leaf leaf-two" /></div></section>
    <section className="trust-strip"><p><span>✦</span> Made for busy IT professionals</p><p><span>✦</span> Simple weekday subscriptions</p><p><span>✦</span> No daily ordering</p></section>
    <section className="section" id="why"><div className="section-heading"><p className="eyebrow">A little bit of home</p><h2>Lunch that fits your workday.</h2><p>We keep it simple: fresh food, a familiar menu, and a reliable pickup at your office.</p></div><div className="feature-grid">{[['⌂','Home cooked','Prepared with the comfort and care of home food.'],['✦','Fresh every day','Lunch is prepared fresh for the day.'],['◌','Made for your workday','Designed around weekday office schedules.'],['↗','Simple plans','No complicated ordering every day.']].map(([icon,title,text]) => <article className="feature" key={title}><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section plans-section" id="plans"><div className="section-heading centered"><p className="eyebrow">Choose your comfort</p><h2>Good food, made easy.</h2><p>Both plans include a complete home-style lunch, Monday to Friday.</p></div><div className="plan-grid">{plans.map(plan => <article className="plan-card" key={plan.name}><div className="plan-head"><div><span className="plan-label">{plan.name.toUpperCase()}</span><h3>{plan.price}<small>/month</small></h3></div><span className="plan-dot" /></div><p className="plan-note">{plan.note}</p><ul>{plan.items.map(item => <li key={item}>✓ {item}</li>)}</ul><Link className="button outline" href={`/order?meal=${plan.name.toLowerCase()}`}>Choose {plan.name}</Link></article>)}</div><div className="trial-banner"><div><p className="eyebrow">Start small</p><h3>Try Grandma&apos;s Lunchbox for 5 days.</h3><p>No payment today. Pay ₹299 on your first delivery and see how good your workday can feel.</p></div><Link className="button light" href="/order?plan=trial">Start 5-day trial <span>→</span></Link></div></section>
    <section className="section menu-section" id="menu"><div className="section-heading centered"><p className="eyebrow">This week&apos;s menu</p><h2>Home-cooked, day by day.</h2><p>Fresh home-style meals planned for every weekday.</p></div><div className="menu-card"><table><thead><tr><th>Day</th><th>Menu</th></tr></thead><tbody>{weeklyMenu.map(({ day, items }) => <tr key={day}><td className="menu-day-cell"><span className="menu-day-name"><span className="menu-day-dot" />{day}</span></td><td className="menu-items-cell"><div className="menu-chips">{items.map(([item, type]) => <span className={`menu-chip ${type}`} key={item}>{item}</span>)}</div></td></tr>)}</tbody></table><p className="menu-foot-note">Menu may vary slightly based on seasonal availability.</p></div></section>
    <section className="section process" id="how"><div className="section-heading centered"><p className="eyebrow">From our kitchen to your desk</p><h2>How it works</h2></div><div className="steps">{[['01','Choose your plan'],['02','Enter your details'],['03','Pay on first delivery'],['04','Collect at ITPL']].map(([number,title],i) => <div className="step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{['Pick Veg or Non-Veg, trial or monthly.','Tell us where you work and where to meet.','No payment today; pay when your first lunch is delivered.','Lunch is ready around 12:30 PM, Monday–Friday.'][i]}</p></div></div>)}</div></section>
    <section className="area-section"><div><p className="eyebrow">Where we deliver</p><h2>ITPL and nearby offices in Whitefield.</h2><p>We&apos;re starting close to home, serving selected ITPL buildings and nearby offices. Choose your building and pickup point during signup.</p><Link className="text-link" href="/order">Check availability <span>→</span></Link></div><div className="map-card"><div className="pin">⌖</div><p><b>ITPL</b><br />Whitefield, Bengaluru</p><small>Currently serving selected pickup points</small></div></section>
    <section className="section faq-section" id="faq"><div className="section-heading centered"><p className="eyebrow">Questions, answered</p><h2>Good to know.</h2></div><div className="faq-grid">{[['What time is lunch delivered?','Around 12:30 PM on weekdays.'],['Which days do you deliver?','Monday to Friday.'],['Can I choose Veg or Non-Veg?','Yes, choose your preference when you place your order.'],['Is there a trial?','Yes, try 5 days for ₹299.'],['How do I receive my lunch?','Select an available building and pickup point during registration.'],['Can I pause my subscription?','Pause and subscription management will be added in a future update.']].map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <footer className="footer"><div className="brand"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Sep%2012%2C%202026%2C%2005_02_26%20PM-nfLMqUqsIl5jluhhngWFv1fIGayTQN.png" alt="Grandma&apos;s Lunchbox logo" /><span>Grandma&apos;s<br /><b>Lunchbox</b></span></div><p>Home-cooked lunch for IT professionals.<br />ITPL & nearby offices, Whitefield, Bengaluru</p><div><b>B VIKAS REDDY</b><br />WhatsApp: 8328286804</div><small>�� 2026 Grandma&apos;s Lunchbox. Made with care.</small></footer>
  </main>
}
